import pandas as pd

tempnagpurl=pd.read_excel(io='Data\Temperature_pandas_labels.xlsx',sheetname='Nagpur')
temppunel=pd.read_excel(io='Data\Temperature_pandas_labels.xlsx',sheetname='Pune')
tempnashikl=pd.read_excel(io='Data\Temperature_pandas_labels.xlsx',sheetname='Nashik')
tempaurangabadl=pd.read_excel(io='Data\Temperature_pandas_labels.xlsx',sheetname='Aurangabad')
tempamravatil=pd.read_excel(io='Data\Temperature_pandas_labels.xlsx',sheetname='Amravati')
tempsolapurl=pd.read_excel(io='Data\Temperature_pandas_labels.xlsx',sheetname='Solapur')
tempyavatmall=pd.read_excel(io='Data\Temperature_pandas_labels.xlsx',sheetname='Yavatmal')
templaturl=pd.read_excel(io='Data\Temperature_pandas_labels.xlsx',sheetname='Latur')

pressnagpurl=pd.read_excel(io='Data\Pressure_pandas_labels.xlsx',sheetname='Nagpur')
presspunel=pd.read_excel(io='Data\Pressure_pandas_labels.xlsx',sheetname='Pune')
pressnashikl=pd.read_excel(io='Data\Pressure_pandas_labels.xlsx',sheetname='Nashik')
pressaurangabadl=pd.read_excel(io='Data\Pressure_pandas_labels.xlsx',sheetname='Aurangabad')
pressamravatil=pd.read_excel(io='Data\Pressure_pandas_labels.xlsx',sheetname='Amravati')
presssolapurl=pd.read_excel(io='Data\Pressure_pandas_labels.xlsx',sheetname='Solapur')
pressyavatmall=pd.read_excel(io='Data\Pressure_pandas_labels.xlsx',sheetname='Yavatmal')
presslaturl=pd.read_excel(io='Data\Pressure_pandas_labels.xlsx',sheetname='Latur')

rfnagpurl=pd.read_excel(io='Data\Rainfall_pandas_labels.xlsx',sheetname='Nagpur')
rfpunel=pd.read_excel(io='Data\Rainfall_pandas_labels.xlsx',sheetname='Pune')
rfnashikl=pd.read_excel(io='Data\Rainfall_pandas_labels.xlsx',sheetname='Nashik')
rfaurangabadl=pd.read_excel(io='Data\Rainfall_pandas_labels.xlsx',sheetname='Aurangabad')
rfamravatil=pd.read_excel(io='Data\Rainfall_pandas_labels.xlsx',sheetname='Amravati')
rfsolapurl=pd.read_excel(io='Data\Rainfall_pandas_labels.xlsx',sheetname='Solapur')
rfyavatmall=pd.read_excel(io='Data\Rainfall_pandas_labels.xlsx',sheetname='Yavatmal')
rflaturl=pd.read_excel(io='Data\Rainfall_pandas_labels.xlsx',sheetname='Latur')

nagpurdroughtyn=pd.read_excel(io='Data\Drought10_pandas_labels.xlsx',sheetname='Nagpur')
punedroughtyn=pd.read_excel(io='Data\Drought10_pandas_labels.xlsx',sheetname='Pune')
nashikdroughtyn=pd.read_excel(io='Data\Drought10_pandas_labels.xlsx',sheetname='Nashik')
aurangabaddroughtyn=pd.read_excel(io='Data\Drought10_pandas_labels.xlsx',sheetname='Aurangabad')
amravatidroughtyn=pd.read_excel(io='Data\Drought10_pandas_labels.xlsx',sheetname='Amravati')
solapurdroughtyn=pd.read_excel(io='Data\Drought10_pandas_labels.xlsx',sheetname='Solapur')
yavatmaldroughtyn=pd.read_excel(io='Data\Drought10_pandas_labels.xlsx',sheetname='Yavatmal')
laturdroughtyn=pd.read_excel(io='Data\Drought10_pandas_labels.xlsx',sheetname='Latur')